//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Mappings configuration element type. Defines the mappings sections needed to define the namespaces _used in the
 *         config file instance_, the datastores with the source feature types, the schema location for the target feature
 *         types and the correspondence between both as mapping elements.
 *       
 * 
 * <p>Java class for AppSchemaDataAccessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppSchemaDataAccessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="namespaces" type="{http://www.geotools.org/app-schema}NamespacesPropertyType"/>
 *         &lt;element name="includedTypes" type="{http://www.geotools.org/app-schema}IncludesPropertyType" minOccurs="0"/>
 *         &lt;element name="sourceDataStores" type="{http://www.geotools.org/app-schema}SourceDataStoresPropertyType"/>
 *         &lt;element name="catalog" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetTypes" type="{http://www.geotools.org/app-schema}TargetTypesPropertyType"/>
 *         &lt;element name="typeMappings" type="{http://www.geotools.org/app-schema}TypeMappingsPropertyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppSchemaDataAccessType", propOrder = {
    "namespaces",
    "includedTypes",
    "sourceDataStores",
    "catalog",
    "targetTypes",
    "typeMappings"
})
public class AppSchemaDataAccessType {

    @XmlElement(required = true)
    protected NamespacesPropertyType namespaces;
    protected IncludesPropertyType includedTypes;
    @XmlElement(required = true)
    protected SourceDataStoresPropertyType sourceDataStores;
    protected String catalog;
    @XmlElement(required = true)
    protected TargetTypesPropertyType targetTypes;
    @XmlElement(required = true)
    protected TypeMappingsPropertyType typeMappings;

    /**
     * Gets the value of the namespaces property.
     * 
     * @return
     *     possible object is
     *     {@link NamespacesPropertyType }
     *     
     */
    public NamespacesPropertyType getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespacesPropertyType }
     *     
     */
    public void setNamespaces(NamespacesPropertyType value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the includedTypes property.
     * 
     * @return
     *     possible object is
     *     {@link IncludesPropertyType }
     *     
     */
    public IncludesPropertyType getIncludedTypes() {
        return includedTypes;
    }

    /**
     * Sets the value of the includedTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludesPropertyType }
     *     
     */
    public void setIncludedTypes(IncludesPropertyType value) {
        this.includedTypes = value;
    }

    /**
     * Gets the value of the sourceDataStores property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDataStoresPropertyType }
     *     
     */
    public SourceDataStoresPropertyType getSourceDataStores() {
        return sourceDataStores;
    }

    /**
     * Sets the value of the sourceDataStores property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDataStoresPropertyType }
     *     
     */
    public void setSourceDataStores(SourceDataStoresPropertyType value) {
        this.sourceDataStores = value;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalog(String value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the targetTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TargetTypesPropertyType }
     *     
     */
    public TargetTypesPropertyType getTargetTypes() {
        return targetTypes;
    }

    /**
     * Sets the value of the targetTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetTypesPropertyType }
     *     
     */
    public void setTargetTypes(TargetTypesPropertyType value) {
        this.targetTypes = value;
    }

    /**
     * Gets the value of the typeMappings property.
     * 
     * @return
     *     possible object is
     *     {@link TypeMappingsPropertyType }
     *     
     */
    public TypeMappingsPropertyType getTypeMappings() {
        return typeMappings;
    }

    /**
     * Sets the value of the typeMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeMappingsPropertyType }
     *     
     */
    public void setTypeMappings(TypeMappingsPropertyType value) {
        this.typeMappings = value;
    }

}
