//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import net.opengis.ogc.BinaryOperatorType;
import net.opengis.ogc.ExpressionType;
import net.opengis.ogc.FunctionType;
import net.opengis.ogc.LiteralType;
import net.opengis.ogc.PropertyNameType;


/**
 * 
 *         
 *       Allows to specify the OGC's Common Query Language expression to be used
 *       as the source for a community schema element's content.
 *     
 *       
 * 
 * <p>Java class for AttributeExpressionMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeExpressionMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="OCQL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="Expression">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.opengis.net/ogc}expression"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="inputAttribute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="linkElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linkField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeExpressionMappingType", propOrder = {
    "ocql",
    "index",
    "expression",
    "inputAttribute",
    "linkElement",
    "linkField"
})
public class AttributeExpressionMappingType {

    @XmlElement(name = "OCQL")
    protected String ocql;
    protected String index;
    @XmlElement(name = "Expression")
    protected AttributeExpressionMappingType.Expression expression;
    protected String inputAttribute;
    protected String linkElement;
    protected String linkField;

    /**
     * Gets the value of the ocql property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCQL() {
        return ocql;
    }

    /**
     * Sets the value of the ocql property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCQL(String value) {
        this.ocql = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeExpressionMappingType.Expression }
     *     
     */
    public AttributeExpressionMappingType.Expression getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeExpressionMappingType.Expression }
     *     
     */
    public void setExpression(AttributeExpressionMappingType.Expression value) {
        this.expression = value;
    }

    /**
     * Gets the value of the inputAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputAttribute() {
        return inputAttribute;
    }

    /**
     * Sets the value of the inputAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputAttribute(String value) {
        this.inputAttribute = value;
    }

    /**
     * Gets the value of the linkElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkElement() {
        return linkElement;
    }

    /**
     * Sets the value of the linkElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkElement(String value) {
        this.linkElement = value;
    }

    /**
     * Gets the value of the linkField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkField() {
        return linkField;
    }

    /**
     * Sets the value of the linkField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkField(String value) {
        this.linkField = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.opengis.net/ogc}expression"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "expression"
    })
    public static class Expression {

        @XmlElementRef(name = "expression", namespace = "http://www.opengis.net/ogc", type = JAXBElement.class)
        protected JAXBElement<?> expression;

        /**
         * Gets the value of the expression property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link FunctionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ExpressionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link LiteralType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyNameType }{@code >}
         *     
         */
        public JAXBElement<?> getExpression() {
            return expression;
        }

        /**
         * Sets the value of the expression property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link FunctionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ExpressionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link LiteralType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryOperatorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyNameType }{@code >}
         *     
         */
        public void setExpression(JAXBElement<?> value) {
            this.expression = ((JAXBElement<?> ) value);
        }

    }

}
