//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 *       Allows to specify the OGC's Common Query Language expression to be used
 *       as the source for a community schema element's content, as long as wether
 *       it is a multivalued property, which target schema element should be created
 *       instead of the default declared on the target schema, and any number
 *       of client properties (aka, xml element attributes)
 *     
 *       
 * 
 * <p>Java class for AttributeMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parentLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetAttribute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetQueryString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idExpression" type="{http://www.geotools.org/app-schema}AttributeExpressionMappingType" minOccurs="0"/>
 *         &lt;element name="sourceExpression" type="{http://www.geotools.org/app-schema}AttributeExpressionMappingType" minOccurs="0"/>
 *         &lt;element name="instancePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetAttributeNode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMultiple" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="encodeIfEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isList" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ClientProperty" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeMappingType", propOrder = {
    "label",
    "parentLabel",
    "targetAttribute",
    "targetQueryString",
    "idExpression",
    "sourceExpression",
    "instancePath",
    "targetAttributeNode",
    "isMultiple",
    "encodeIfEmpty",
    "isList",
    "clientProperty"
})
public class AttributeMappingType {

    protected String label;
    protected String parentLabel;
    @XmlElement(required = true)
    protected String targetAttribute;
    protected String targetQueryString;
    protected AttributeExpressionMappingType idExpression;
    protected AttributeExpressionMappingType sourceExpression;
    protected String instancePath;
    protected String targetAttributeNode;
    @XmlElement(defaultValue = "false")
    protected Boolean isMultiple;
    @XmlElement(defaultValue = "false")
    protected Boolean encodeIfEmpty;
    @XmlElement(defaultValue = "false")
    protected Boolean isList;
    @XmlElement(name = "ClientProperty")
    protected List<AttributeMappingType.ClientProperty> clientProperty;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the parentLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentLabel() {
        return parentLabel;
    }

    /**
     * Sets the value of the parentLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentLabel(String value) {
        this.parentLabel = value;
    }

    /**
     * Gets the value of the targetAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAttribute() {
        return targetAttribute;
    }

    /**
     * Sets the value of the targetAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAttribute(String value) {
        this.targetAttribute = value;
    }

    /**
     * Gets the value of the targetQueryString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetQueryString() {
        return targetQueryString;
    }

    /**
     * Sets the value of the targetQueryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetQueryString(String value) {
        this.targetQueryString = value;
    }

    /**
     * Gets the value of the idExpression property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeExpressionMappingType }
     *     
     */
    public AttributeExpressionMappingType getIdExpression() {
        return idExpression;
    }

    /**
     * Sets the value of the idExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeExpressionMappingType }
     *     
     */
    public void setIdExpression(AttributeExpressionMappingType value) {
        this.idExpression = value;
    }

    /**
     * Gets the value of the sourceExpression property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeExpressionMappingType }
     *     
     */
    public AttributeExpressionMappingType getSourceExpression() {
        return sourceExpression;
    }

    /**
     * Sets the value of the sourceExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeExpressionMappingType }
     *     
     */
    public void setSourceExpression(AttributeExpressionMappingType value) {
        this.sourceExpression = value;
    }

    /**
     * Gets the value of the instancePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstancePath() {
        return instancePath;
    }

    /**
     * Sets the value of the instancePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstancePath(String value) {
        this.instancePath = value;
    }

    /**
     * Gets the value of the targetAttributeNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAttributeNode() {
        return targetAttributeNode;
    }

    /**
     * Sets the value of the targetAttributeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAttributeNode(String value) {
        this.targetAttributeNode = value;
    }

    /**
     * Gets the value of the isMultiple property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMultiple() {
        return isMultiple;
    }

    /**
     * Sets the value of the isMultiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMultiple(Boolean value) {
        this.isMultiple = value;
    }

    /**
     * Gets the value of the encodeIfEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEncodeIfEmpty() {
        return encodeIfEmpty;
    }

    /**
     * Sets the value of the encodeIfEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEncodeIfEmpty(Boolean value) {
        this.encodeIfEmpty = value;
    }

    /**
     * Gets the value of the isList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsList() {
        return isList;
    }

    /**
     * Sets the value of the isList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsList(Boolean value) {
        this.isList = value;
    }

    /**
     * Gets the value of the clientProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clientProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClientProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeMappingType.ClientProperty }
     * 
     * 
     */
    public List<AttributeMappingType.ClientProperty> getClientProperty() {
        if (clientProperty == null) {
            clientProperty = new ArrayList<AttributeMappingType.ClientProperty>();
        }
        return this.clientProperty;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "value"
    })
    public static class ClientProperty {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
