//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 *       This is only needed if this type has related types that do not have their own 
 *       Geoserver configuration, ie. not published in Geoserver. The type might be
 *       mapped separately so they can be reusable (feature chaining concept), e.g. 
 *       If feature type A contains data type B, and feature type C also contains
 *       data type B, we only want to have one mapping file for data type B. 
 *  
 *       The purpose of this is so that the parent type (this mapping) can find the
 *       related features.
 *       The type might not be visible on their own because it's not a feature type
 *       (e.g. a data type), therefore shouldn't appear in requests such as GetCapabilities,
 *       DescribeFeatureType etc. 
 *     
 * 		
 * 
 * <p>Java class for IncludesPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncludesPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Include" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncludesPropertyType", propOrder = {
    "include"
})
public class IncludesPropertyType {

    @XmlElement(name = "Include")
    protected List<Object> include;

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getInclude() {
        if (include == null) {
            include = new ArrayList<Object>();
        }
        return this.include;
    }

}
