//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 *     Here you have to specify lo location of the different xsd schema files that comprises
 *     the community schema. You have to specify each and every involved/relevant xsd schema
 *     since the current schema parser does not has the ability of following includes and imports.
 *     Also, it would be very helpful if they're declared in the more sequential fashion possible, since
 *     even if the schema parser uses proxied types when it finds a type reference that haven't still
 *     been loaded, setting schema file locations in random order could lead to missing referencing 
 *     of nested types and thus causing an unrecoverable parsing time error.
 *     
 *     As for supported GML 3.1.1 types, complex datastore automatically loads the following gml schema files
 *     before parsing the community schemas, so if you need more gml types just add them prior to your
 *     own schemas:
 *       basicTypes.xsd
 *       gmlBase.xsd
 *       dictionary.xsd
 *       valueObjects.xsd
 *       coverage.xsd     
 *       measures.xsd
 *       geometryBasic0d1d.xsd
 *     
 *     Note that though not all the geometry schemas are loaded, you don't need to import the corresponding
 *     gml schemas for geometry types since (at least for SFS) they're already supported by the geotools type system.
 *     
 *       
 * 
 * <p>Java class for TargetTypesPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetTypesPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="schemaUri" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetTypesPropertyType", propOrder = {
    "featureType"
})
public class TargetTypesPropertyType {

    @XmlElement(name = "FeatureType")
    protected TargetTypesPropertyType.FeatureType featureType;

    /**
     * Gets the value of the featureType property.
     * 
     * @return
     *     possible object is
     *     {@link TargetTypesPropertyType.FeatureType }
     *     
     */
    public TargetTypesPropertyType.FeatureType getFeatureType() {
        return featureType;
    }

    /**
     * Sets the value of the featureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetTypesPropertyType.FeatureType }
     *     
     */
    public void setFeatureType(TargetTypesPropertyType.FeatureType value) {
        this.featureType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="schemaUri" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schemaUri"
    })
    public static class FeatureType {

        protected List<String> schemaUri;

        /**
         * Gets the value of the schemaUri property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the schemaUri property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSchemaUri().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSchemaUri() {
            if (schemaUri == null) {
                schemaUri = new ArrayList<String>();
            }
            return this.schemaUri;
        }

    }

}
