//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:40:56 PM CEST 
//


package org.geotools.app_schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 *     This is where tha magis happens. The prior sections were just support information for getting 
 *     to this instance. Inside this section, you have to declare one FeatureTypeMapping element
 *     for each feature type you want to map from an internal structure to the community schema.
 *     The FeatureTypeMapping element contains information as what is the internat feature type
 *     you want to map (given by the datastore id and feature type name), the name of the target
 *     element in the community schema you want to serve, and the attribute mappings between them.
 *     
 *       
 * 
 * <p>Java class for TypeMappingsPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeMappingsPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureTypeMapping" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mappingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sourceDataStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="targetElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="itemXpath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="isXmlDataStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="isDenormalised" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="attributeMappings" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AttributeMapping" type="{http://www.geotools.org/app-schema}AttributeMappingType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeMappingsPropertyType", propOrder = {
    "featureTypeMapping"
})
public class TypeMappingsPropertyType {

    @XmlElement(name = "FeatureTypeMapping")
    protected List<TypeMappingsPropertyType.FeatureTypeMapping> featureTypeMapping;

    /**
     * Gets the value of the featureTypeMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureTypeMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureTypeMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeMappingsPropertyType.FeatureTypeMapping }
     * 
     * 
     */
    public List<TypeMappingsPropertyType.FeatureTypeMapping> getFeatureTypeMapping() {
        if (featureTypeMapping == null) {
            featureTypeMapping = new ArrayList<TypeMappingsPropertyType.FeatureTypeMapping>();
        }
        return this.featureTypeMapping;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mappingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sourceDataStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="targetElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="itemXpath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="isXmlDataStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="isDenormalised" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="attributeMappings" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AttributeMapping" type="{http://www.geotools.org/app-schema}AttributeMappingType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mappingName",
        "sourceDataStore",
        "sourceType",
        "targetElement",
        "itemXpath",
        "isXmlDataStore",
        "isDenormalised",
        "attributeMappings"
    })
    public static class FeatureTypeMapping {

        protected String mappingName;
        @XmlElement(required = true)
        protected String sourceDataStore;
        @XmlElement(required = true)
        protected String sourceType;
        @XmlElement(required = true)
        protected String targetElement;
        protected String itemXpath;
        @XmlElement(defaultValue = "false")
        protected Boolean isXmlDataStore;
        @XmlElement(defaultValue = "true")
        protected Boolean isDenormalised;
        protected TypeMappingsPropertyType.FeatureTypeMapping.AttributeMappings attributeMappings;

        /**
         * Gets the value of the mappingName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMappingName() {
            return mappingName;
        }

        /**
         * Sets the value of the mappingName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMappingName(String value) {
            this.mappingName = value;
        }

        /**
         * Gets the value of the sourceDataStore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceDataStore() {
            return sourceDataStore;
        }

        /**
         * Sets the value of the sourceDataStore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceDataStore(String value) {
            this.sourceDataStore = value;
        }

        /**
         * Gets the value of the sourceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceType() {
            return sourceType;
        }

        /**
         * Sets the value of the sourceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceType(String value) {
            this.sourceType = value;
        }

        /**
         * Gets the value of the targetElement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetElement() {
            return targetElement;
        }

        /**
         * Sets the value of the targetElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetElement(String value) {
            this.targetElement = value;
        }

        /**
         * Gets the value of the itemXpath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemXpath() {
            return itemXpath;
        }

        /**
         * Sets the value of the itemXpath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemXpath(String value) {
            this.itemXpath = value;
        }

        /**
         * Gets the value of the isXmlDataStore property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIsXmlDataStore() {
            return isXmlDataStore;
        }

        /**
         * Sets the value of the isXmlDataStore property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsXmlDataStore(Boolean value) {
            this.isXmlDataStore = value;
        }

        /**
         * Gets the value of the isDenormalised property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIsDenormalised() {
            return isDenormalised;
        }

        /**
         * Sets the value of the isDenormalised property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsDenormalised(Boolean value) {
            this.isDenormalised = value;
        }

        /**
         * Gets the value of the attributeMappings property.
         * 
         * @return
         *     possible object is
         *     {@link TypeMappingsPropertyType.FeatureTypeMapping.AttributeMappings }
         *     
         */
        public TypeMappingsPropertyType.FeatureTypeMapping.AttributeMappings getAttributeMappings() {
            return attributeMappings;
        }

        /**
         * Sets the value of the attributeMappings property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeMappingsPropertyType.FeatureTypeMapping.AttributeMappings }
         *     
         */
        public void setAttributeMappings(TypeMappingsPropertyType.FeatureTypeMapping.AttributeMappings value) {
            this.attributeMappings = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AttributeMapping" type="{http://www.geotools.org/app-schema}AttributeMappingType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeMapping"
        })
        public static class AttributeMappings {

            @XmlElement(name = "AttributeMapping")
            protected List<AttributeMappingType> attributeMapping;

            /**
             * Gets the value of the attributeMapping property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeMapping property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeMapping().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AttributeMappingType }
             * 
             * 
             */
            public List<AttributeMappingType> getAttributeMapping() {
                if (attributeMapping == null) {
                    attributeMapping = new ArrayList<AttributeMappingType>();
                }
                return this.attributeMapping;
            }

        }

    }

}
